### ISSUE TITLE
WeasyPrint could not import some external libraries. 

### ISSUE THREAD

**Issue by bbecausereasonss** [assafelovic/gpt-researcher#22]
Win11x64 Python 3.10 Conda

WeasyPrint could not import some external libraries. Please carefully follow the installation steps before reporting an issue:
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#installation
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#troubleshooting

-----

Process SpawnProcess-1:
Traceback (most recent call last):
  File "C:\Users\xxxx\anaconda3\envs\gpt-researcher\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\xxxx\anaconda3\envs\gpt-researcher\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\xxxx\anaconda3\envs\gpt-researcher\lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\xxxx\anaconda3\envs\gpt-researcher\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\xxxx\anaconda3\envs\gpt-researcher\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\xxxx\anaconda3\envs\gpt-researcher\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\xxxx\anaconda3\envs\gpt-researcher\lib\site-packages\uvicorn\server.py", line 68, in serve
    config.load()
  File "C:\Users\xxxx\anaconda3\envs\gpt-researcher\lib\site-packages\uvicorn\config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "C:\Users\xxxx\anaconda3\envs\gpt-researcher\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Users\xxxx\anaconda3\envs\gpt-researcher\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\xxxx\Deep\gpt-researcher\main.py", line 8, in <module>
    from agent.run import WebSocketManager
  File "C:\Users\xxxx\Deep\gpt-researcher\agent\run.py", line 7, in <module>
    from agent.research_agent import ResearchAgent
  File "C:\Users\xxxx\Deep\gpt-researcher\agent\research_agent.py", line 7, in <module>
    from actions.web_scrape import async_browse
  File "C:\Users\xxxx\Deep\gpt-researcher\actions\web_scrape.py", line 23, in <module>
    import processing.text as summary
  File "C:\Users\xxxx\Deep\gpt-researcher\processing\text.py", line 11, in <module>
    from md2pdf.core import md2pdf
  File "C:\Users\xxxx\anaconda3\envs\gpt-researcher\lib\site-packages\md2pdf\__init__.py", line 7, in <module>
    from .core import md2pdf  # noqa
  File "C:\Users\xxxx\anaconda3\envs\gpt-researcher\lib\site-packages\md2pdf\core.py", line 5, in <module>
    from weasyprint import HTML, CSS
  File "C:\Users\xxxx\anaconda3\envs\gpt-researcher\lib\site-packages\weasyprint\__init__.py", line 387, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip
  File "C:\Users\xxxx\anaconda3\envs\gpt-researcher\lib\site-packages\weasyprint\css\__init__.py", line 25, in <module>
    from . import computed_values, counters, media_queries
  File "C:\Users\xxxx\anaconda3\envs\gpt-researcher\lib\site-packages\weasyprint\css\computed_values.py", line 11, in <module>
    from ..text.ffi import ffi, pango, units_to_double
  File "C:\Users\xxxx\anaconda3\envs\gpt-researcher\lib\site-packages\weasyprint\text\ffi.py", line 428, in <module>
    gobject = _dlopen(
  File "C:\Users\xxxx\anaconda3\envs\gpt-researcher\lib\site-packages\weasyprint\text\ffi.py", line 417, in _dlopen
    return ffi.dlopen(names[0])  # pragma: no cover
  File "C:\Users\xxxx\anaconda3\envs\gpt-researcher\lib\site-packages\cffi\api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "C:\Users\xxxx\anaconda3\envs\gpt-researcher\lib\site-packages\cffi\api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "C:\Users\xxxx\anaconda3\envs\gpt-researcher\lib\site-packages\cffi\api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'gobject-2.0-0': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'

**Comment by bbecausereasonss** [comment]
Once I followed weasyprint instructions and restarted my computer, now I get a warning.

(process:21572): GLib-GIO-WARNING **: 07:56:17.463: Unexpectedly, UWP app `Microsoft.ScreenSketch_11.2305.25.0_x64__8wekyb3d8bbwe' (AUMId `Microsoft.ScreenSketch_8wekyb3d8bbwe!App') supports 29 extensions but has no verbs

**Comment by bbecausereasonss** [comment]
Also.

An error occurred while processing the url https://hbr.org/2023/05/a-new-approach-to-building-your-personal-brand: File is not a zip file
An error occurred while processing the url https://brenits.com/fundame ntals-of-developing-a-strong-personal-brand/: Message: 'chromedriver.exe' executable may have wrong permissions. Please see https://chromedriver.chromium.org/home

An error occurred while processing the url https://hbr.org/2022/02/whats-the-point-of-a-personal-brand: Message: unknown error: Chrome failed to start: was killed.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location C:\Program Files\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
Backtrace:
        GetHandleVerifier [0x00BFA813+48355]
        (No symbol) [0x00B8C4B1]
        (No symbol) [0x00A95358]
        (No symbol) [0x00AB3621]
        (No symbol) [0x00AB0579]
        (No symbol) [0x00AE0C55]
        (No symbol) [0x00AE093C]
        (No symbol) [0x00ADA536]
        (No symbol) [0x00AB82DC]
        (No symbol) [0x00AB93DD]
        GetHandleVerifier [0x00E5AABD+2539405]
        GetHandleVerifier [0x00E9A78F+2800735]
        GetHandleVerifier [0x00E9456C+2775612]
        GetHandleVerifier [0x00C851E0+616112]
        (No symbol) [0x00B95F8C]
        (No symbol) [0x00B92328]
        (No symbol) [0x00B9240B]
        (No symbol) [0x00B84FF7]
        BaseThreadInitThunk [0x76817D59+25]
        RtlInitializeExceptionChain [0x77C9B79B+107]
        RtlClearBits [0x77C9B71F+191]

An error occurred while processing the url https://www.coursera.org/learn/personal-branding: Message: unknown error: Chrome failed to start: was killed.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location C:\Program Files\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
Backtrace:
        GetHandleVerifier [0x00BFA813+48355]
        (No symbol) [0x00B8C4B1]
        (No symbol) [0x00A95358]
        (No symbol) [0x00AB3621]
        (No symbol) [0x00AB0579]
        (No symbol) [0x00AE0C55]
        (No symbol) [0x00AE093C]
        (No symbol) [0x00ADA536]
        (No symbol) [0x00AB82DC]
        (No symbol) [0x00AB93DD]
        GetHandleVerifier [0x00E5AABD+2539405]
        GetHandleVerifier [0x00E9A78F+2800735]
        GetHandleVerifier [0x00E9456C+2775612]
        GetHandleVerifier [0x00C851E0+616112]
        (No symbol) [0x00B95F8C]
        (No symbol) [0x00B92328]
        (No symbol) [0x00B9240B]
        (No symbol) [0x00B84FF7]
        BaseThreadInitThunk [0x76817D59+25]
        RtlInitializeExceptionChain [0x77C9B79B+107]
        RtlClearBits [0x77C9B71F+191]

ERROR:    Exception in ASGI application

**Comment by Grantham00** [comment]
Are you using pip from within the conda environment?
Try creating a new environment with pip installed, then go into that and install requirements.
`conda create -n myenv pip`
`conda activate myenv`
`pip install -r requirements.txt`

If that doesn't work, in a new env you could try using conda install to install weasyprint before you install the rest of requirements.
`conda install -c conda-forge weasyprint`.

Lastly, in the conda env you'll need to set your API key, I did it with an environment variable 
`conda env config vars set OPENAI_API_KEY=value`

**Comment by bbecausereasonss** [comment]
Yep was using pip. Will try using Conda install.

**Comment by assafelovic** [comment]
Hey @bbecausereasonss did installing conda solve your issue?

**Comment by bbecausereasonss** [comment]
> Hey @bbecausereasonss did installing conda solve your issue?

Unfortunately not... I installed via conda install -c conda-forge weasyprint
and still getting same errors. Might try in WSL later...

(gpt-researcher) PS C:\Users\xxxx\Deep\gpt-researcher> uvicorn main:app --reload
INFO:     Will watch for changes in these directories: ['C:\\Users\\xxxx\\Deep\\gpt-researcher']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [20856] using StatReload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "C:\Users\xxxx\anaconda3\envs\gpt-researcher\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\xxxx\anaconda3\envs\gpt-researcher\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\xxxx\anaconda3\envs\gpt-researcher\lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\xxxx\anaconda3\envs\gpt-researcher\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\xxxx\anaconda3\envs\gpt-researcher\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\xxxx\anaconda3\envs\gpt-researcher\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\xxxx\anaconda3\envs\gpt-researcher\lib\site-packages\uvicorn\server.py", line 68, in serve
    config.load()
  File "C:\Users\xxxx\anaconda3\envs\gpt-researcher\lib\site-packages\uvicorn\config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "C:\Users\xxxx\anaconda3\envs\gpt-researcher\lib\site-packages\uvicorn\importer.py", line 24, in import_from_string
    raise exc from None
  File "C:\Users\xxxx\anaconda3\envs\gpt-researcher\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Users\xxxx\anaconda3\envs\gpt-researcher\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\xxxx\Deep\gpt-researcher\main.py", line 8, in <module>
    from agent.run import WebSocketManager
  File "C:\Users\xxxx\Deep\gpt-researcher\agent\run.py", line 7, in <module>
    from agent.research_agent import ResearchAgent
  File "C:\Users\xxxx\Deep\gpt-researcher\agent\research_agent.py", line 7, in <module>
    from actions.web_scrape import async_browse
  File "C:\Users\xxxx\Deep\gpt-researcher\actions\web_scrape.py", line 23, in <module>
    import processing.text as summary
  File "C:\Users\xxxx\Deep\gpt-researcher\processing\text.py", line 11, in <module>
    from md2pdf.core import md2pdf
  File "C:\Users\xxxx\anaconda3\envs\gpt-researcher\lib\site-packages\md2pdf\__init__.py", line 7, in <module>
    from .core import md2pdf  # noqa
  File "C:\Users\xxxx\anaconda3\envs\gpt-researcher\lib\site-packages\md2pdf\core.py", line 5, in <module>
    from weasyprint import HTML, CSS
  File "C:\Users\xxxx\anaconda3\envs\gpt-researcher\lib\site-packages\weasyprint\__init__.py", line 388, in <module>
    from .html import (  # noqa isort:skip
  File "C:\Users\xxxx\anaconda3\envs\gpt-researcher\lib\site-packages\weasyprint\html.py", line 26, in <module>
    from .images import SVGImage
  File "C:\Users\xxxx\anaconda3\envs\gpt-researcher\lib\site-packages\weasyprint\images.py", line 16, in <module>
    from PIL import Image, ImageFile, ImageOps
  File "C:\Users\xxxx\anaconda3\envs\gpt-researcher\lib\site-packages\PIL\Image.py", line 103, in <module>
    from . import _imaging as core
ImportError: DLL load failed while importing _imaging: The specified module could not be found.

**Comment by hunterphillips** [comment]
I had better results after installing WeasyPrint with Brew, per another thread - https://github.com/assafelovic/gpt-researcher/issues/25

`brew install weasyprint`

**Comment by bbecausereasonss** [comment]
> 

I'm in windows..

**Comment by chaoscreater** [comment]
I'm using Conda as well and interestly, the error I got is different:

`OSError: cannot load library 'pangoft2-1.0-0': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'pangoft2-1.0-0'`

**Comment by rotemweiss57** [comment]
Hi @chaoscreater , this error simply says you don't have access to gpt-4. you will have access at the end of the month as per this post by openai: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4. In the meanwhile, please refer to this post as a workaround: https://github.com/assafelovic/gpt-researcher/issues/14 

Hope it helps!

**Comment by chaoscreater** [comment]
> Hi @chaoscreater , this error simply says you don't have access to gpt-4. you will have access at the end of the month as per this post by openai: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4. In the meanwhile, please refer to this post as a workaround: #14
> 
> Hope it helps!

I've had access to gpt4 for ages. I'm on chatgpt plus and using openai api key and all my other apps and projects use gpt4 just fine. I even have access to the latest code interpreter plugin.
