### ISSUE TITLE
Open AI Key

### ISSUE THREAD

**Issue by speenoo** [assafelovic/gpt-researcher#222]
Having issues with my openai key. No matter what I do it still wont work. Ive tried exporting, putting it in the .env, and manually placing it in the config file. Im running on windows. Has anyone faced this issue? I saw someone else having it in the discord.

Our main issue here:
`gpt-researcher-gpt-researcher-1  |   File "/usr/src/app/agent/run.py", line 43, in run_agent
gpt-researcher-gpt-researcher-1  |     check_config_setup()
gpt-researcher-gpt-researcher-1  |   File "/usr/src/app/config/config.py", line 110, in check_config_setup
gpt-researcher-gpt-researcher-1  |     check_openai_api_key(cfg)
gpt-researcher-gpt-researcher-1  |   File "/usr/src/app/config/config.py", line 123, in check_openai_api_key
gpt-researcher-gpt-researcher-1  |     raise APIKeyError("OpenAI")
gpt-researcher-gpt-researcher-1  | config.config.APIKeyError: Please set your OpenAI API key in .env or as an environment variable.
gpt-researcher-gpt-researcher-1  | You can get your key from https://platform.openai.com/account/api-keys`

Entire Error
`gpt-researcher-gpt-researcher-1  | Traceback (most recent call last):
gpt-researcher-gpt-researcher-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/websockets/wsproto_impl.py", line 234, in run_asgi       
gpt-researcher-gpt-researcher-1  |     result = await self.app(self.scope, self.receive, self.send)
gpt-researcher-gpt-researcher-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gpt-researcher-gpt-researcher-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
gpt-researcher-gpt-researcher-1  |     return await self.app(scope, receive, send)
gpt-researcher-gpt-researcher-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gpt-researcher-gpt-researcher-1  |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1115, in __call__
gpt-researcher-gpt-researcher-1  |     await super().__call__(scope, receive, send)
gpt-researcher-gpt-researcher-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
gpt-researcher-gpt-researcher-1  |     await self.middleware_stack(scope, receive, send)
gpt-researcher-gpt-researcher-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 149, in __call__
gpt-researcher-gpt-researcher-1  |     await self.app(scope, receive, send)
gpt-researcher-gpt-researcher-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
gpt-researcher-gpt-researcher-1  |     raise exc
gpt-researcher-gpt-researcher-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
gpt-researcher-gpt-researcher-1  |     await self.app(scope, receive, sender)
gpt-researcher-gpt-researcher-1  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
gpt-researcher-gpt-researcher-1  |     raise e
gpt-researcher-gpt-researcher-1  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
gpt-researcher-gpt-researcher-1  |     await self.app(scope, receive, send)
gpt-researcher-gpt-researcher-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
gpt-researcher-gpt-researcher-1  |     await route.handle(scope, receive, send)
gpt-researcher-gpt-researcher-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 341, in handle
gpt-researcher-gpt-researcher-1  |     await self.app(scope, receive, send)
gpt-researcher-gpt-researcher-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 82, in app
gpt-researcher-gpt-researcher-1  |     await func(session)
gpt-researcher-gpt-researcher-1  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 325, in app
gpt-researcher-gpt-researcher-1  |     await dependant.call(**values)
gpt-researcher-gpt-researcher-1  |   File "/usr/src/app/main.py", line 60, in websocket_endpoint
gpt-researcher-gpt-researcher-1  |     await manager.start_streaming(task, report_type, agent, agent_role_prompt, websocket)
gpt-researcher-gpt-researcher-1  |   File "/usr/src/app/agent/run.py", line 38, in start_streaming
gpt-researcher-gpt-researcher-1  |     report, path = await run_agent(task, report_type, agent, agent_role_prompt, websocket)
gpt-researcher-gpt-researcher-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gpt-researcher-gpt-researcher-1  |   File "/usr/src/app/agent/run.py", line 43, in run_agent
gpt-researcher-gpt-researcher-1  |     check_config_setup()
gpt-researcher-gpt-researcher-1  |   File "/usr/src/app/config/config.py", line 110, in check_config_setup
gpt-researcher-gpt-researcher-1  |     check_openai_api_key(cfg)
gpt-researcher-gpt-researcher-1  |   File "/usr/src/app/config/config.py", line 123, in check_openai_api_key
gpt-researcher-gpt-researcher-1  |     raise APIKeyError("OpenAI")
gpt-researcher-gpt-researcher-1  | config.config.APIKeyError: Please set your OpenAI API key in .env or as an environment variable.
gpt-researcher-gpt-researcher-1  | You can get your key from https://platform.openai.com/account/api-keys`

**Comment by speenoo** [comment]
fixed. no idea what fixed it, but just started working all of a sudden
