### ISSUE TITLE
SyntaxError: invalid syntax when running uvicorn main:app --reload

### ISSUE THREAD

**Issue by glejdis** [assafelovic/gpt-researcher#266]
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [62124] using StatReload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "c:\users\xx\appdata\local\programs\python\python37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "c:\users\xx\appdata\local\programs\python\python37\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\xx\appdata\local\programs\python\python37\lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "c:\users\xx\appdata\local\programs\python\python37\lib\site-packages\uvicorn\server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "c:\users\xx\appdata\local\programs\python\python37\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "c:\users\xx\appdata\local\programs\python\python37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\users\xx\appdata\local\programs\python\python37\lib\site-packages\uvicorn\server.py", line 66, in serve
    config.load()
  File "c:\users\xx\appdata\local\programs\python\python37\lib\site-packages\uvicorn\config.py", line 471, in load
    self.loaded_app = import_from_string(self.app)
  File "c:\users\xx\appdata\local\programs\python\python37\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string       
    module = importlib.import_module(module_str)
  File "c:\users\xx\appdata\local\programs\python\python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\xx\Desktop\gpt-researcher-master\main.py", line 1, in <module>
    from backend.server import app
  File "C:\Users\xx\Desktop\gpt-researcher-master\backend\server.py", line 7, in <module>
    from gpt_researcher.utils.websocket_manager import WebSocketManager
  File "C:\Users\xx\Desktop\gpt-researcher-master\gpt_researcher\__init__.py", line 1, in <module>
    from .master import GPTResearcher
  File "C:\Users\x\Desktop\gpt-researcher-master\gpt_researcher\master\__init__.py", line 1, in <module>
    from .agent import GPTResearcher
  File "C:\Users\xx\Desktop\gpt-researcher-master\gpt_researcher\master\agent.py", line 3, in <module>
    from gpt_researcher.master.functions import *
  File "C:\Users\xx\Desktop\gpt-researcher-master\gpt_researcher\master\functions.py", line 18
    match retriever:
                  ^
SyntaxError: invalid syntax

**Comment by assafelovic** [comment]
Hey @glejdis can you try upgrading your Python to 3.11 and try again?

**Comment by callumcui** [comment]
I have same issue, I'm sure, my python version is 3.11

**Comment by assafelovic** [comment]
@callumcui can you share the error logs?
