### ISSUE TITLE
400 Client Error: Bad Request for url: https://api.tavily.com/search

### ISSUE THREAD

**Issue by scottiesan** [assafelovic/gpt-researcher#307]
It made 6 request before it failed.  Is there a limit on the api?  I don't see it on their documentation.  We need to implement a fallback on the searches

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/scott/miniconda3/envs/research/lib/python3.11/site-packages/uvicorn/protocols/websockets/wsproto_impl.py", line 234, in run_asgi
    result = await self.app(self.scope, self.receive, self.send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/scott/miniconda3/envs/research/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/scott/miniconda3/envs/research/lib/python3.11/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/scott/miniconda3/envs/research/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/scott/miniconda3/envs/research/lib/python3.11/site-packages/starlette/middleware/errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "/Users/scott/miniconda3/envs/research/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/scott/miniconda3/envs/research/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/scott/miniconda3/envs/research/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/Users/scott/miniconda3/envs/research/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/Users/scott/miniconda3/envs/research/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/scott/miniconda3/envs/research/lib/python3.11/site-packages/starlette/routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "/Users/scott/miniconda3/envs/research/lib/python3.11/site-packages/starlette/routing.py", line 82, in app
    await func(session)
  File "/Users/scott/miniconda3/envs/research/lib/python3.11/site-packages/fastapi/routing.py", line 325, in app
    await dependant.call(**values)
  File "/Users/scott/Desktop/DEV/ResearchGPT/gpt-researcher/backend/server.py", line 50, in websocket_endpoint
    report = await manager.start_streaming(task, report_type, websocket)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/scott/Desktop/DEV/ResearchGPT/gpt-researcher/gpt_researcher/utils/websocket_manager.py", line 51, in start_streaming
    report = await run_agent(task, report_type, websocket)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/scott/Desktop/DEV/ResearchGPT/gpt-researcher/gpt_researcher/utils/websocket_manager.py", line 63, in run_agent
    report = await researcher.run()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/scott/Desktop/DEV/ResearchGPT/gpt-researcher/gpt_researcher/master/agent.py", line 48, in run
    self.context = await self.get_context_by_search(self.query)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/scott/Desktop/DEV/ResearchGPT/gpt-researcher/gpt_researcher/master/agent.py", line 87, in get_context_by_search
    scraped_sites = await self.scrape_sites_by_query(sub_query)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/scott/Desktop/DEV/ResearchGPT/gpt-researcher/gpt_researcher/master/agent.py", line 121, in scrape_sites_by_query
    search_results = retriever.search(max_results=self.cfg.max_search_results_per_query)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/scott/Desktop/DEV/ResearchGPT/gpt-researcher/gpt_researcher/retrievers/tavily_search/tavily_search.py", line 43, in search
    results = self.client.search(self.query, search_depth="advanced", max_results=max_results)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/scott/miniconda3/envs/research/lib/python3.11/site-packages/tavily/tavily.py", line 47, in search
    return self._search(query, search_depth=search_depth, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/scott/miniconda3/envs/research/lib/python3.11/site-packages/tavily/tavily.py", line 41, in _search
    response.raise_for_status()  # Raises a HTTPError if the HTTP request returned an unsuccessful status code
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/scott/miniconda3/envs/research/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.tavily.com/search

**Comment by assafelovic** [comment]
Hey @scottiesan is the issue still persisting?

**Comment by shaojun** [comment]
I've seen this error as well, I'm using the free account of tavily. just random, like 3 times in 10 queries.
