### ISSUE TITLE
Bad Request - https://api.tavily.com/search 

### ISSUE THREAD

**Issue by normandmickey** [assafelovic/gpt-researcher#332]
I built a basic Flask app using the GPT-Research package. It was working fine yesterday, however today I have been getting a bad request error.  I thought it might be a temporary problem but I have tried several times and keep getting this error. 
 

Traceback (most recent call last):
  File "C:\Users\norma\OddsAPI\.venv\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\norma\OddsAPI\.venv\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\norma\OddsAPI\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\norma\OddsAPI\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\norma\OddsAPI\app.py", line 127, in chatgpt_prediction
    report = asyncio.run(get_report(query, report_type))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\norma\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\norma\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\norma\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "c:\Users\norma\OddsAPI\app.py", line 35, in get_report
    report = await researcher.run()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\norma\OddsAPI\.venv\Lib\site-packages\gpt_researcher\master\agent.py", line 48, in run
    self.context = await self.get_context_by_search(self.query)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\norma\OddsAPI\.venv\Lib\site-packages\gpt_researcher\master\agent.py", line 87, in get_context_by_search
    scraped_sites = await self.scrape_sites_by_query(sub_query)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\norma\OddsAPI\.venv\Lib\site-packages\gpt_researcher\master\agent.py", line 121, in scrape_sites_by_query
    search_results = retriever.search(max_results=self.cfg.max_search_results_per_query)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\norma\OddsAPI\.venv\Lib\site-packages\gpt_researcher\retrievers\tavily_search\tavily_search.py", line 43, in search
    results = self.client.search(self.query, search_depth="advanced", max_results=max_results)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\norma\OddsAPI\.venv\Lib\site-packages\tavily\tavily.py", line 47, in search
    return self._search(query, search_depth=search_depth, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\norma\OddsAPI\.venv\Lib\site-packages\tavily\tavily.py", line 41, in _search
    response.raise_for_status()  # Raises a HTTPError if the HTTP request returned an unsuccessful status code
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\norma\OddsAPI\.venv\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.tavily.com/search

**Comment by normandmickey** [comment]
According to the documentation we can use a different search engine by changing the provider.  I tried "googleAPI" and it didn't work.  When I set SEARCH_RETRIEVER="google" it worked (with the appropriate GOOGLE_API_KEY and GOOGLE_CX_KEY).  You should consider changing the documentation.  It would be nice to be able so set a fallback search retriever. 

https://docs.tavily.com/docs/gpt-researcher/getting-started
For search engine, we recommend [Tavily Search API](https://app.tavily.com/) (optimized for LLMs), but you can also refer to other search engines of your choice by changing the search provider in config/config.py to "duckduckgo", **"googleAPI",** "googleSerp", or "searx". Then add the corresponding env API key as seen in the config.py file.

**Comment by assafelovic** [comment]
@normandmickey can you check if you've reached your API limit?

**Comment by assafelovic** [comment]
Generally it's always advisable to add fallback requests to other search providers. Thanks for raising it :)
