### ISSUE TITLE
ImportError: cannot import name 'ArxivScraper' from partially initialized module 'gpt_researcher.scraper.scraper'

### ISSUE THREAD

**Issue by ParkJaeSeong** [assafelovic/gpt-researcher#390]
Thank you for the great program.

An execution error occurred after the recent git pull.

Both pip and poetry have been updated.

Please help.

Ubuntu 22.04.4 LTS
python 3.11.8

'''
❯ python -m uvicorn main:app --reload
INFO:     Will watch for changes in these directories: ['/home/jspark/git/gpt-researcher']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [154125] using WatchFiles
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/home/jspark/git/pyenv/versions/3.11.8/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/jspark/git/pyenv/versions/3.11.8/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jspark/git/pyenv/versions/3.11.8/envs/venv/lib/python3.11/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/jspark/git/pyenv/versions/3.11.8/envs/venv/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jspark/git/pyenv/versions/3.11.8/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/jspark/git/pyenv/versions/3.11.8/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/jspark/git/pyenv/versions/3.11.8/envs/venv/lib/python3.11/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/jspark/git/pyenv/versions/3.11.8/envs/venv/lib/python3.11/site-packages/uvicorn/config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jspark/git/pyenv/versions/3.11.8/envs/venv/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jspark/git/pyenv/versions/3.11.8/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/jspark/git/gpt-researcher/main.py", line 1, in <module>
    from backend.server import app
  File "/home/jspark/git/gpt-researcher/backend/server.py", line 7, in <module>
    from gpt_researcher.utils.websocket_manager import WebSocketManager
  File "/home/jspark/git/gpt-researcher/gpt_researcher/__init__.py", line 1, in <module>
    from .master import GPTResearcher
  File "/home/jspark/git/gpt-researcher/gpt_researcher/master/__init__.py", line 1, in <module>
    from .agent import GPTResearcher
  File "/home/jspark/git/gpt-researcher/gpt_researcher/master/agent.py", line 3, in <module>
    from gpt_researcher.master.functions import *
  File "/home/jspark/git/gpt-researcher/gpt_researcher/master/functions.py", line 3, in <module>
    from gpt_researcher.scraper import Scraper
  File "/home/jspark/git/gpt-researcher/gpt_researcher/scraper/__init__.py", line 1, in <module>
    from .scraper import Scraper
  File "/home/jspark/git/gpt-researcher/gpt_researcher/scraper/scraper.py", line 6, in <module>
    from .scraper import (
ImportError: cannot import name 'ArxivScraper' from partially initialized module 'gpt_researcher.scraper.scraper' (most likely due to a circular import) (/home/jspark/git/gpt-researcher/gpt_researcher/scraper/scraper.py)
'''

**Comment by nileshtrivedi** [comment]
I am facing this too with Python v3.12.1 (managed via `asdf`) and mac os.

**Comment by assafelovic** [comment]
Should be fixed now with latest PR: https://github.com/assafelovic/gpt-researcher/pull/392

Can you please help verify that it works now? @nileshtrivedi  @ParkJaeSeong

**Comment by nileshtrivedi** [comment]
@assafelovic Yes, the app starts fine with the latest commit. 👍 

Thanks for the quick fix! 👏

**Comment by assafelovic** [comment]
Great!
