### ISSUE TITLE
AzureOpenAI - error generating subtopics in detailed mode

### ISSUE THREAD

**Issue by Xtrah** [assafelovic/gpt-researcher#422]
To use AzureOpenAI, I have the following `.env`:
```
EMBEDDING_PROVIDER=azureopenai
LLM_PROVIDER=azureopenai
SMART_LLM_MODEL=gpt-4-0125-preview
AZURE_OPENAI_API_KEY=REDACTED
AZURE_OPENAI_ENDPOINT=https://REDACTED.openai.azure.com/
OPENAI_API_VERSION=2024-02-01
AZURE_EMBEDDING_MODEL=text-embedding-3-large
OPENAI_API_TYPE="azure"
TAVILY_API_KEY=REDACTED
```

Running short and fast mode works fine. 

However, detailed mode stops working when it starts generating subtopics:

```
🤔 Generating subtopics...

🤖 Calling gpt-4-0125-preview...

Exception in parsing subtopics :  1 validation error for ChatOpenAI
__root__
  Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass `openai_api_key` as a named parameter. (type=value_error)
📋Subtopics: []
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/websockets/wsproto_impl.py", line 233, in run_asgi
    result = await self.app(self.scope, self.receive, self.send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 151, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 373, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 96, in app
    await wrap_app_handling_exceptions(app, session)(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 94, in app
    await func(session)
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 348, in app
    await dependant.call(**values)
  File "/usr/src/app/backend/server.py", line 50, in websocket_endpoint
    report = await manager.start_streaming(task, report_type, websocket)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/gpt_researcher/utils/websocket_manager.py", line 57, in start_streaming
    report = await run_agent(task, report_type, websocket)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/gpt_researcher/utils/websocket_manager.py", line 75, in run_agent
    report = await researcher.run()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/gpt_researcher/report_type/detailed_report/detailed_report.py", line 36, in run
    subtopics = await self._get_all_subtopics()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/gpt_researcher/report_type/detailed_report/detailed_report.py", line 62, in _get_all_subtopics
    return subtopics.dict()["subtopics"]
           ^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'dict'
```

So it seems like the subtopic generator isn't using the specified LLM provider (Azure), as it still requests an `OPENAI_API_KEY`..?

**Comment by assafelovic** [comment]
And it works with the short research? @Xtrah

**Comment by Xtrah** [comment]
Yes it does.

**Comment by deb1305** [comment]
I am trying to configure azure open ai variables, but facing some problem with the configuration. Can someone share the config.py file?

**Comment by Xtrah** [comment]
> I am trying to configure azure open ai variables, but facing some problem with the configuration. Can someone share the config.py file?

The only changes to config.py I used is listed above. I also have a `.env` with the following:

```
AZURE_OPENAI_API_KEY=REDACTED
AZURE_OPENAI_ENDPOINT=https://REDACTED.openai.azure.com/
OPENAI_API_VERSION=2024-02-01
AZURE_EMBEDDING_MODEL=text-embedding-3-large
OPENAI_API_TYPE="azure"
TAVILY_API_KEY=REDACTED
```

**Comment by Xtrah** [comment]
Updated the main post. Same error when only using `.env` file, but cleaner not using both .env and config.py for changes!

**Comment by assafelovic** [comment]
@norrisp90 can you give a hand here? I don't have an Azure account

**Comment by norrisp90** [comment]
HI @assafelovic I'm looking into it. At first review it appears that the call too:

`File"/usr/src/app/gpt_researcher/report_type/detailed_report/detailed_report.py", line 36, in run subtopics = await self._get_all_subtopics()`

Is not enforcing the fact that the LLM provider type has been set to "azure" and defaulting back to trying to call an OpenAI API endpoint. The actual error is:

`Exception in parsing subtopics :  Error code: 401 - {'error': {'message': 'Incorrect API key provided: XXX*******************XXX. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}`

Which comes from the OpenAI API endpoint, not an Azure one. I'll try and figure out were we need to remind it of the fact we're using Azure OpenAI.

**Comment by assafelovic** [comment]
Fyi @proy9714

**Comment by norrisp90** [comment]
@assafelovic @proy9714  In utils/llm.py line 126 we seem to hardcode the use if OpenAI only in construct_subtopics(), model = ChatOpeAI() will only use the OpenAI API, we should probably change to use the LLM provider pattern?

`async def construct_subtopics(task: str, data: str, config, subtopics: list = []) -> list:
    try:
        parser = PydanticOutputParser(pydantic_object=Subtopics)

        prompt = PromptTemplate(
            template=generate_subtopics_prompt(),
            input_variables=["task", "data", "subtopics", "max_subtopics"],
            partial_variables={
                "format_instructions": parser.get_format_instructions()},
        )

        print(f"\n🤖 Calling {config.smart_llm_model}...\n")

        **model = ChatOpenAI(model=config.smart_llm_model)**

        chain = prompt | model | parser

        output = chain.invoke({
            "task": task,
            "data": data,
            "subtopics": subtopics,
            "max_subtopics": config.max_subtopics
        })

        return output`

**Comment by norrisp90** [comment]
@assafelovic & @proy9714 #432 provides a hotfix to support LLM_Provider = azureopenai.

**Comment by assafelovic** [comment]
Thank you @norrisp90 ! Fixed here: https://github.com/assafelovic/gpt-researcher/pull/432
