### ISSUE TITLE
Error generating outputs (pdf, docx, md)

### ISSUE THREAD

**Issue by uniqueNY85** [assafelovic/gpt-researcher#474]
I cloned the repo and have the app working. It is successfully researching and generating a report in the UI, however, no "copy to clipboard" or "download" button appears. Furthermore, I'm getting errors relating to converting to these formats, and nothing shows up in the output folder. Here's the output from my terminal. 

✍️ Writing summary for research task: Research the new 80/20 rul regarding HCBS Care Worker Payment Requirements...
Error in converting Markdown to PDF: [Errno 2] No such file or directory: 'outputs/task_1715100812_Research the new 80/20 rul regarding HCBS Care Worker Payment Requirements.pdf'
Error in converting Markdown to DOCX: [Errno 2] No such file or directory: 'outputs/task_1715100812_Research the new 80/20 rul regarding HCBS Care Worker Payment Requirements.docx'
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\gpt_researcher\gpt_research_venv\Lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 240, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\gpt_researcher\gpt_research_venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\gpt_researcher\gpt_research_venv\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\gpt_researcher\gpt_research_venv\Lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\gpt_researcher\gpt_research_venv\Lib\site-packages\starlette\middleware\errors.py", line 151, in __call__
    await self.app(scope, receive, send)
  File "C:\gpt_researcher\gpt_research_venv\Lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\gpt_researcher\gpt_research_venv\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\gpt_researcher\gpt_research_venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\gpt_researcher\gpt_research_venv\Lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\gpt_researcher\gpt_research_venv\Lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "C:\gpt_researcher\gpt_research_venv\Lib\site-packages\starlette\routing.py", line 373, in handle
    await self.app(scope, receive, send)
  File "C:\gpt_researcher\gpt_research_venv\Lib\site-packages\starlette\routing.py", line 96, in app
    await wrap_app_handling_exceptions(app, session)(scope, receive, send)
  File "C:\gpt_researcher\gpt_research_venv\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\gpt_researcher\gpt_research_venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\gpt_researcher\gpt_research_venv\Lib\site-packages\starlette\routing.py", line 94, in app
    await func(session)
  File "C:\gpt_researcher\gpt_research_venv\Lib\site-packages\fastapi\routing.py", line 348, in app
    await dependant.call(**values)
  File "C:\gpt_researcher\gpt-researcher\backend\server.py", line 58, in websocket_endpoint
    md_path = await write_text_to_md(report, filename)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\gpt_researcher\gpt-researcher\backend\utils.py", line 32, in write_text_to_md
    await write_to_file(file_path, text)
  File "C:\gpt_researcher\gpt-researcher\backend\utils.py", line 19, in write_to_file
    async with aiofiles.open(filename, "w", encoding='utf-8') as file:
  File "C:\gpt_researcher\gpt_research_venv\Lib\site-packages\aiofiles\base.py", line 98, in __aenter__
    self._obj = await self._coro
                ^^^^^^^^^^^^^^^^
  File "C:\gpt_researcher\gpt_research_venv\Lib\site-packages\aiofiles\threadpool\__init__.py", line 94, in _open
    f = yield from loop.run_in_executor(executor, cb)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'outputs/task_1715100812_Research the new 80/20 rul regarding HCBS Care Worker Payment Requirements.md'
INFO:     connection closed

**Comment by uniqueNY85** [comment]
I think this has to do with the length of the query as that's being used in the file name. So for a long query, the generated reports fail, but it works for a short query. That "/" in "80/20" in my above example may also be what's causing the issue.

**Comment by assafelovic** [comment]
Hey @uniqueNY85 just fixed in latest commit https://github.com/assafelovic/gpt-researcher/commit/836fea9b763814b36c075b11fa21f0d7f2d0a1b8

Please pull latest and should work
