### ISSUE TITLE
Incorrect setting of alternative base_url for ChatOpenAI

### ISSUE THREAD

**Issue by mmashnev** [assafelovic/gpt-researcher#511]
I encountered an error while attempting to configure an alternative OpenAI base URL via the environment parameter `OPENAI_BASE_URL`. The error log is attached below for reference.

Error Log:

```
2024-05-20 19:34:12 INFO:     ('172.18.0.1', 56588) - "WebSocket /ws" [accepted]
2024-05-20 19:34:12 INFO:     connection open
2024-05-20 19:34:19 ERROR:    Exception in ASGI application
2024-05-20 19:34:19 Traceback (most recent call last):
2024-05-20 19:34:19   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 240, in run_asgi
2024-05-20 19:34:19     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
2024-05-20 19:34:19              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-20 19:34:19   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
2024-05-20 19:34:19     return await self.app(scope, receive, send)
2024-05-20 19:34:19            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-20 19:34:19   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-05-20 19:34:19     await super().__call__(scope, receive, send)
2024-05-20 19:34:19   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
2024-05-20 19:34:19     await self.middleware_stack(scope, receive, send)
2024-05-20 19:34:19   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 151, in __call__
2024-05-20 19:34:19     await self.app(scope, receive, send)
2024-05-20 19:34:19   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-05-20 19:34:19     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-05-20 19:34:19   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-05-20 19:34:19     raise exc
2024-05-20 19:34:19   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-05-20 19:34:19     await app(scope, receive, sender)
2024-05-20 19:34:19   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
2024-05-20 19:34:19     await self.middleware_stack(scope, receive, send)
2024-05-20 19:34:19   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
2024-05-20 19:34:19     await route.handle(scope, receive, send)
2024-05-20 19:34:19   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 373, in handle
2024-05-20 19:34:19     await self.app(scope, receive, send)
2024-05-20 19:34:19   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 96, in app
2024-05-20 19:34:19     await wrap_app_handling_exceptions(app, session)(scope, receive, send)
2024-05-20 19:34:19   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-05-20 19:34:19     raise exc
2024-05-20 19:34:19   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-05-20 19:34:19     await app(scope, receive, sender)
2024-05-20 19:34:19   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 94, in app
2024-05-20 19:34:19     await func(session)
2024-05-20 19:34:19   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 348, in app
2024-05-20 19:34:19     await dependant.call(**values)
2024-05-20 19:34:19   File "/usr/src/app/backend/server.py", line 53, in websocket_endpoint
2024-05-20 19:34:19     report = await manager.start_streaming(task, report_type, report_source, websocket)
2024-05-20 19:34:19              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-20 19:34:19   File "/usr/src/app/backend/websocket_manager.py", line 57, in start_streaming
2024-05-20 19:34:19     report = await run_agent(task, report_type, report_source, websocket)
2024-05-20 19:34:19              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-20 19:34:19   File "/usr/src/app/backend/websocket_manager.py", line 75, in run_agent
2024-05-20 19:34:19     report = await researcher.run()
2024-05-20 19:34:19              ^^^^^^^^^^^^^^^^^^^^^^
2024-05-20 19:34:19   File "/usr/src/app/backend/report_type/basic_report/basic_report.py", line 18, in run
2024-05-20 19:34:19     await researcher.conduct_research()
2024-05-20 19:34:19   File "/usr/src/app/gpt_researcher/master/agent.py", line 94, in conduct_research
2024-05-20 19:34:19     context = await self.get_context_by_search(self.query)
2024-05-20 19:34:19               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-20 19:34:19   File "/usr/src/app/gpt_researcher/master/agent.py", line 161, in get_context_by_search
2024-05-20 19:34:19     sub_queries = await get_sub_queries(query, self.role, self.cfg, self.parent_query, self.report_type)
2024-05-20 19:34:19                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-20 19:34:19   File "/usr/src/app/gpt_researcher/master/functions.py", line 95, in get_sub_queries
2024-05-20 19:34:19     response = await create_chat_completion(
2024-05-20 19:34:19                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-20 19:34:19   File "/usr/src/app/gpt_researcher/utils/llm.py", line 71, in create_chat_completion
2024-05-20 19:34:19     provider = ProviderClass(
2024-05-20 19:34:19                ^^^^^^^^^^^^^^
2024-05-20 19:34:19   File "/usr/src/app/gpt_researcher/llm_provider/openai/openai.py", line 20, in __init__
2024-05-20 19:34:19     self.llm = self.get_llm_model()
2024-05-20 19:34:19                ^^^^^^^^^^^^^^^^^^^^
2024-05-20 19:34:19   File "/usr/src/app/gpt_researcher/llm_provider/openai/openai.py", line 55, in get_llm_model
2024-05-20 19:34:19     llm.base_url = self.base_url
2024-05-20 19:34:19     ^^^^^^^^^^^^
2024-05-20 19:34:19   File "/usr/local/lib/python3.11/site-packages/pydantic/v1/main.py", line 357, in __setattr__
2024-05-20 19:34:19     raise ValueError(f'"{self.__class__.__name__}" object has no field "{name}"')
2024-05-20 19:34:19 ValueError: "ChatOpenAI" object has no field "base_url"
2024-05-20 19:34:19 INFO:     connection closed
```

The issue appears to stem from the use of `base_url` as an alias for the `openai_api_base` field in the ChatOpenAI class. While base_url can be used in the constructor, it seems that it cannot be used when setting fields directly. This discrepancy is likely causing the error.

**Steps to Reproduce:**
1. Set the `OPENAI_BASE_URL` environment variable to an alternative OpenAI base URL.
2. Run the application.
3. Make any research query.
4. Observe the error in the log.

**Expected Behavior:**
The application should correctly use the `OPENAI_BASE_URL` to configure the OpenAI base URL without errors.

**Actual Behavior:**
The application throws an error due to the incorrect usage of the alias `base_url` when setting fields directly.

**Proposed Solution:**
Use the field name `openai_api_base` instead of the alias `base_url` when setting fields directly.

**Comment by amrpyt** [comment]
any solution?

**Comment by mmashnev** [comment]
> any solution?
Sure, I opened PR #512 with the fix

**Comment by amrpyt** [comment]
> > any solution?
> 
> 
> 
> Sure, I opened PR #512 with the fix
> 
> 

Can you tell me the solution and how to implement it?

Cuz i tried so much putting the `base_url` as environment variable in `.env` but it gives me the error : `ValueError: "ChatOpenAI" object has no field "base_url"`

**Comment by Jallermax** [comment]
@amrpyt To pass the environment variable from .env you should add it to docker-compoes.yml like this:
```yaml
services:
  gpt-researcher:
    image: kramer1346/gpt-researcher
    build: ./
    environment: 
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      TAVILY_API_KEY: ${TAVILY_API_KEY}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL}
```

**Comment by smartnikocj** [comment]
how to solve this issue?
