### ISSUE TITLE
ERROR:    Exception in ASGI application

### ISSUE THREAD

**Issue by simoncarlson11** [assafelovic/gpt-researcher#56]
Research appears to run but then throws this error:
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/simonc/.local/lib/python3.8/site-packages/uvicorn/protocols/websockets/wsproto_impl.py", line 249, in run_asgi
    result = await self.app(self.scope, self.receive, self.send)
  File "/home/simonc/.local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/simonc/.local/lib/python3.8/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/home/simonc/.local/lib/python3.8/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/simonc/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "/home/simonc/.local/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/simonc/.local/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/simonc/.local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/simonc/.local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/simonc/.local/lib/python3.8/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/simonc/.local/lib/python3.8/site-packages/starlette/routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "/home/simonc/.local/lib/python3.8/site-packages/starlette/routing.py", line 82, in app
    await func(session)
  File "/home/simonc/.local/lib/python3.8/site-packages/fastapi/routing.py", line 324, in app
    await dependant.call(**values)
  File "/home/simonc/gpt-researcher/main.py", line 50, in websocket_endpoint
    await manager.start_streaming(task, report_type, agent, websocket)
  File "/home/simonc/gpt-researcher/agent/run.py", line 38, in start_streaming
    report, path = await run_agent(task, report_type, agent, websocket)
  File "/home/simonc/gpt-researcher/agent/run.py", line 50, in run_agent
    await assistant.conduct_research()
  File "/home/simonc/gpt-researcher/agent/research_agent.py", line 137, in conduct_research
    search_queries = await self.create_search_queries()
  File "/home/simonc/gpt-researcher/agent/research_agent.py", line 92, in create_search_queries
    return json.loads(result)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 42)

**Comment by rotemweiss57** [comment]
Hi Simon, please refer to this discussion: https://github.com/assafelovic/gpt-researcher/issues/14 

Let me know if you got it to work!

**Comment by simoncarlson11** [comment]
Thank you so much. yes I made the changes as per the discussion and now it
is fully working with the GTP-3.5 model. I have a paid subscription to
OpenAPI so I'm not sure why GPT-4 isn't working but that's not your issue.
I'll post an update on linkedin as well. Thanks for your support and
tireless work on this.

**Comment by rotemweiss57** [comment]
Hi @simoncarlson11 I'm happy to hear that! your GPT-4 will start working from next months. They only gave access to users who paid at least one bill: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4
