### ISSUE TITLE
Can't run - needs exa-py

### ISSUE THREAD

**Issue by sonicviz** [assafelovic/gpt-researcher#634]
Followed the documentation to run locally.
Changed .env file correctly, but get error below.

Solution:
Need to add exa-py to requirement.txt dependencies

ERROR:    Exception in ASGI application
Traceback (most recent call last):
....
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Source Control\AI RAG Frameworks\gpt-researcher\gpt_researcher\master\actions.py", line 49, in get_retriever
    from gpt_researcher.retrievers import TavilySearch
  File "E:\Source Control\AI RAG Frameworks\gpt-researcher\gpt_researcher\retrievers\__init__.py", line 4, in <module>
    from .exa.exa import ExaSearch
  File "E:\Source Control\AI RAG Frameworks\gpt-researcher\gpt_researcher\retrievers\exa\exa.py", line 3, in <module>
    from exa_py import Exa
ModuleNotFoundError: No module named 'exa_py'

**Comment by assafelovic** [comment]
@sonicviz please pull latest and run `pip install -r requirements.txt` 
Fix in latest commit: https://github.com/assafelovic/gpt-researcher/commit/c5fe4756d040fd7568d8b7195014478293dcc5e3

**Comment by sonicviz** [comment]
kk, ty
