### ISSUE TITLE
llama3 keyerror 'server'

### ISSUE THREAD

**Issue by Abdullahaml1** [assafelovic/gpt-researcher#701]
I faces this Error during running gpt-researcher.
* I am using the latest version (github)
my `.env` file
```bash
EMBEDDING_PROVIDER=ollama
# Specify one of the embedding models supported by Ollama
OLLAMA_EMBEDDING_MODEL=nomic-embed-text
# Use ollama for both, LLM and EMBEDDING provider
LLM_PROVIDER=ollama

# Ollama endpoint to use
OLLAMA_BASE_URL=http://localhost:11434

# Specify one of the LLM models supported by Ollama
FAST_LLM_MODEL=llama3:70b
# Specify one of the LLM models supported by Ollama
SMART_LLM_MODEL=llama3:70b
# The temperature to use, defaults to 0.55
TEMPERATURE=0.55
# Retriver
RETRIEVER=tavily
```

The error itself
```
$ uvicorn main:app
INFO:     Started server process [1211335]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     156.218.212.11:0 - "GET / HTTP/1.1" 200 OK
INFO:     156.218.212.11:0 - "GET /static/gptr-logo.png HTTP/1.1" 304 Not Modified
INFO:     156.218.212.11:0 - "GET /site/scripts.js HTTP/1.1" 304 Not Modified
INFO:     156.218.212.11:0 - "GET / HTTP/1.1" 200 OK
INFO:     ('156.218.212.11', 0) - "WebSocket /ws" [accepted]
INFO:     connection open
🔎 Starting the research task for 'Automatic Speech Recognition SOTA Models'...
⚠️ Error in reading JSON, attempting to repair JSON
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/wakeb/text-workspace/gpt-researcher/gpt_researcher/master/actions.py", line 107, in choose_agent
    agent_dict = json.loads(response)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/home/wakeb/miniconda3/envs/gpt-research/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wakeb/miniconda3/envs/gpt-research/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wakeb/miniconda3/envs/gpt-research/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wakeb/miniconda3/envs/gpt-research/lib/python3.11/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 244, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wakeb/miniconda3/envs/gpt-research/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wakeb/miniconda3/envs/gpt-research/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/wakeb/miniconda3/envs/gpt-research/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/wakeb/miniconda3/envs/gpt-research/lib/python3.11/site-packages/starlette/middleware/errors.py", line 151, in __call__
    await self.app(scope, receive, send)
  File "/home/wakeb/miniconda3/envs/gpt-research/lib/python3.11/site-packages/starlette/middleware/cors.py", line 77, in __call__
    await self.app(scope, receive, send)
  File "/home/wakeb/miniconda3/envs/gpt-research/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/wakeb/miniconda3/envs/gpt-research/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/wakeb/miniconda3/envs/gpt-research/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/wakeb/miniconda3/envs/gpt-research/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/wakeb/miniconda3/envs/gpt-research/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/home/wakeb/miniconda3/envs/gpt-research/lib/python3.11/site-packages/starlette/routing.py", line 373, in handle
    await self.app(scope, receive, send)
  File "/home/wakeb/miniconda3/envs/gpt-research/lib/python3.11/site-packages/starlette/routing.py", line 96, in app
    await wrap_app_handling_exceptions(app, session)(scope, receive, send)
  File "/home/wakeb/miniconda3/envs/gpt-research/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/wakeb/miniconda3/envs/gpt-research/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/wakeb/miniconda3/envs/gpt-research/lib/python3.11/site-packages/starlette/routing.py", line 94, in app
    await func(session)
  File "/home/wakeb/miniconda3/envs/gpt-research/lib/python3.11/site-packages/fastapi/routing.py", line 348, in app
    await dependant.call(**values)
  File "/home/wakeb/text-workspace/gpt-researcher/backend/server.py", line 88, in websocket_endpoint
    report = await manager.start_streaming(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wakeb/text-workspace/gpt-researcher/backend/websocket_manager.py", line 60, in start_streaming
    report = await run_agent(task, report_type, report_source, tone, websocket, headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wakeb/text-workspace/gpt-researcher/backend/websocket_manager.py", line 85, in run_agent
    report = await researcher.run()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wakeb/text-workspace/gpt-researcher/backend/report_type/detailed_report/detailed_report.py", line 59, in run
    await self._initial_research()
  File "/home/wakeb/text-workspace/gpt-researcher/backend/report_type/detailed_report/detailed_report.py", line 80, in _initial_research
    await self.main_task_assistant.conduct_research()
  File "/home/wakeb/text-workspace/gpt-researcher/gpt_researcher/master/agent.py", line 109, in conduct_research
    self.agent, self.role = await choose_agent(
                            ^^^^^^^^^^^^^^^^^^^
  File "/home/wakeb/text-workspace/gpt-researcher/gpt_researcher/master/actions.py", line 112, in choose_agent
    return await handle_json_error(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wakeb/text-workspace/gpt-researcher/gpt_researcher/master/actions.py", line 127, in handle_json_error
    return json_data["server"], json_data["agent_role_prompt"]
           ~~~~~~~~~^^^^^^^^^^
KeyError: 'server'
INFO:     connection closed
```

I think the error because gpt-researcher assume to return JSON, but it got text, so the problem might be in prompt format for llama3. Suffixing the prompt by return the answer in JSON might solves the problem [see](https://github.com/ollama/ollama/blob/main/docs/api.md#request-2)

**Comment by assafelovic** [comment]
It definitely seems like llama3 is not returning a valid JSON. Would love a PR to resolve this in case you can @Abdullahaml1 . I have not worked enough with llama3 to push this

**Comment by assafelovic** [comment]
This should be resolved now
