### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by will-deeplearn** [assafelovic/gpt-researcher#732]
It's my first time to run the project and after I entered the question and clicked "Research", the agent output showed " 🤔 Thinking about research questions for the task..." and had the following errors.

INFO:    127.0.0.1:58668 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:58668 - "GET /site/styles.css HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:58669 - "GET /static/gptr-logo.png HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:58668 - "GET /site/scripts.js HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:58668 - "GET /static/favicon.ico HTTP/1.1" 304 Not Modified
INFO:     ('127.0.0.1', 58673) - "WebSocket /ws" [accepted]
INFO:     connection open
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\jianxing\anaconda3\Lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 244, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jianxing\anaconda3\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jianxing\anaconda3\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\jianxing\anaconda3\Lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\jianxing\anaconda3\Lib\site-packages\starlette\middleware\errors.py", line 151, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\jianxing\anaconda3\Lib\site-packages\starlette\middleware\cors.py", line 77, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\jianxing\anaconda3\Lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\jianxing\anaconda3\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\jianxing\anaconda3\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\jianxing\anaconda3\Lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\jianxing\anaconda3\Lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "C:\Users\jianxing\anaconda3\Lib\site-packages\starlette\routing.py", line 373, in handle
    await self.app(scope, receive, send)
  File "C:\Users\jianxing\anaconda3\Lib\site-packages\starlette\routing.py", line 96, in app
    await wrap_app_handling_exceptions(app, session)(scope, receive, send)
  File "C:\Users\jianxing\anaconda3\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\jianxing\anaconda3\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\jianxing\anaconda3\Lib\site-packages\starlette\routing.py", line 94, in app
    await func(session)
  File "C:\Users\jianxing\anaconda3\Lib\site-packages\fastapi\routing.py", line 348, in app
    await dependant.call(**values)
  File "E:\gpt-researcher\backend\server.py", line 89, in websocket_endpoint
    report = await manager.start_streaming(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\gpt-researcher\backend\websocket_manager.py", line 60, in start_streaming
    report = await run_agent(task, report_type, report_source, source_urls, tone, websocket, headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\gpt-researcher\backend\websocket_manager.py", line 97, in run_agent
    report = await researcher.run()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\gpt-researcher\backend\report_type\basic_report\basic_report.py", line 41, in run
    await researcher.conduct_research()
  File "E:\gpt-researcher\gpt_researcher\master\agent.py", line 103, in conduct_research
    await stream_output(
  File "E:\gpt-researcher\gpt_researcher\master\actions.py", line 463, in stream_output
    print(output)
UnicodeEncodeError: 'gbk' codec can't encode character '\U0001f50e' in position 0: illegal multibyte sequence
INFO:     connection closed
INFO:     ('127.0.0.1', 58675) - "WebSocket /ws" [accepted]
INFO:     connection open
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\jianxing\anaconda3\Lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 244, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jianxing\anaconda3\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jianxing\anaconda3\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\jianxing\anaconda3\Lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\jianxing\anaconda3\Lib\site-packages\starlette\middleware\errors.py", line 151, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\jianxing\anaconda3\Lib\site-packages\starlette\middleware\cors.py", line 77, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\jianxing\anaconda3\Lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\jianxing\anaconda3\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\jianxing\anaconda3\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\jianxing\anaconda3\Lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\jianxing\anaconda3\Lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "C:\Users\jianxing\anaconda3\Lib\site-packages\starlette\routing.py", line 373, in handle
    await self.app(scope, receive, send)
  File "C:\Users\jianxing\anaconda3\Lib\site-packages\starlette\routing.py", line 96, in app
    await wrap_app_handling_exceptions(app, session)(scope, receive, send)
  File "C:\Users\jianxing\anaconda3\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\jianxing\anaconda3\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\jianxing\anaconda3\Lib\site-packages\starlette\routing.py", line 94, in app
    await func(session)
  File "C:\Users\jianxing\anaconda3\Lib\site-packages\fastapi\routing.py", line 348, in app
    await dependant.call(**values)
  File "E:\gpt-researcher\backend\server.py", line 89, in websocket_endpoint
    report = await manager.start_streaming(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\gpt-researcher\backend\websocket_manager.py", line 60, in start_streaming
    report = await run_agent(task, report_type, report_source, source_urls, tone, websocket, headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\gpt-researcher\backend\websocket_manager.py", line 97, in run_agent
    report = await researcher.run()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\gpt-researcher\backend\report_type\basic_report\basic_report.py", line 41, in run
    await researcher.conduct_research()
  File "E:\gpt-researcher\gpt_researcher\master\agent.py", line 103, in conduct_research
    await stream_output(
  File "E:\gpt-researcher\gpt_researcher\master\actions.py", line 463, in stream_output
    print(output)
UnicodeEncodeError: 'gbk' codec can't encode character '\U0001f50e' in position 0: illegal multibyte sequence
INFO:     connection closed

**Comment by assafelovic** [comment]
Hey @kitty-elephant can you share what was your initial research query?

**Comment by kitty-elephant** [comment]
> Hey @kitty-elephant can you share what was your initial research query?

At first I used Chinese to query, and then I restarted the project and tried English like "Is the cryptocurrency market suitable for adding positions now?". Both of them have the above problems.

**Comment by afern247** [comment]
I can confirm, my first try as well and getting the same error

**Comment by ElishaKay** [comment]
Welcome @kitty-elephant @afern247 

I had a similar issue yesterday and we [pushed up a fix here in actions.py](https://github.com/assafelovic/gpt-researcher/commit/8b36f62356e4f8375b47602fc900c88f57d33d02#diff-d1206bfbeebe88f76a35a4adaa03de9f51de4d7519c02654e1329ec5445dba8f)

Both cases are UnicodeEncodeError instances, occurring when trying to print Unicode characters that can't be encoded using the default character encoding of the console.

The recommended fix & path of least resistance is to run via Docker (even if you've never used it before)

[Try this flow](https://github.com/assafelovic/gpt-researcher?tab=readme-ov-file#run-with-docker)

**Comment by ElishaKay** [comment]
Seems to be resolved - please feel free to re-open this ticket if the issue persists
