### ISSUE TITLE
When running it

### ISSUE THREAD

**Issue by rossman22590** [assafelovic/gpt-researcher#750]
Process SpawnProcess-1:
Traceback (most recent call last):
  File "D:\anaconda\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "D:\anaconda\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\anaconda\Lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "D:\anaconda\Lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "D:\anaconda\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\Lib\asyncio\base_events.py", line 653, in run_until_complete        
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\anaconda\Lib\site-packages\uvicorn\server.py", line 68, in serve
    config.load()
  File "D:\anaconda\Lib\site-packages\uvicorn\config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\Lib\site-packages\uvicorn\importer.py", line 24, in import_from_string
    raise exc from None
  File "D:\anaconda\Lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "c:\Users\Ross\Desktop\gpt-researcher-master\gpt-researcher-master\main.py", line 1, in <module>
    from backend.server import app
  File "c:\Users\Ross\Desktop\gpt-researcher-master\gpt-researcher-master\backend\__init__.py", line 1, in <module>
    from multi_agents import agents
  File "c:\Users\Ross\Desktop\gpt-researcher-master\gpt-researcher-master\multi_agents\__init__.py", line 3, in <module>
    from .agents import (
  File "c:\Users\Ross\Desktop\gpt-researcher-master\gpt-researcher-master\multi_agents\agents\__init__.py", line 6, in <module>
    from .editor import EditorAgent
  File "c:\Users\Ross\Desktop\gpt-researcher-master\gpt-researcher-master\multi_agents\agents\editor.py", line 4, in <module>
    from langgraph.graph import StateGraph, END
ModuleNotFoundError: No module named 'langgraph'

**Comment by assafelovic** [comment]
You need to install the directories dependencies. Run `pip install -r requirements.txt` within the multi_agents folder.

**Comment by rossman22590** [comment]
i use docker compose up.
