### ISSUE TITLE
"outline report" doesn't work

### ISSUE THREAD

**Issue by elchananvol** [assafelovic/gpt-researcher#799]
"Outline Report" from report types doesn't work. it has internal problem with tone argument. 
The problem occurs whether you use the tone argument in "researcher = GPTResearcher(query, report_type, tone)" or not.

here the relevant Traceback 
```
Traceback (most recent call last):
  File "C:\Users\elcha\researcher_streamlit1\app.py", line 222, in <module>
    report = asyncio.run(get_report(prompt, report_type_dict[report_type], tone))
  File "C:\Users\elcha\researcher_streamlit1\app.py", line 52, in get_report
    report = await researcher.write_report()
  File "C:\Users\elcha\resercher_streamlit\.venv\researcher_streamlit1\Lib\site-packages\gpt_researcher\master\agent.py", line 207, in write_report
    report = await generate_report(
  File "C:\Users\elcha\resercher_streamlit\.venv\researcher_streamlit1\Lib\site-packages\gpt_researcher\master\actions.py", line 428, in generate_report
    content = f"{generate_prompt(query, context, report_source, report_format=cfg.report_format, tone=tone, total_words=cfg.total_words)}"
                
TypeError: generate_outline_report_prompt() got an unexpected keyword argument 'tone'
```
Code of mine function get report is 
```
async def get_report(query: str, report_type: str, tone) -> str:
    researcher = GPTResearcher(query, report_type, tone)
    research_result = await researcher.conduct_research()
    report = await researcher.write_report()
    return report
```

**Comment by assafelovic** [comment]
Pushed a fix please try again thank you!
