### ISSUE TITLE
Error when trying to use an OLLAMA instance that is not on the same system as gpt-researcher

### ISSUE THREAD

**Issue by mdlmarkham** [assafelovic/gpt-researcher#820]
**Describe the bug**
When I install GPT-Researcher on a Ubuntu environment and try to configure Ollama as the LLM_Provider with an OLLAMA_BASE_URL that is not localhost, the logs show that GPT-RESEARCHER is looking for OLLAMA locally:

```
" Traceback (most recent call last):
  File "/root/gpt-researcher/gpt_researcher/master/actions.py", line 139, in choose_agent
    response = await create_chat_completion(
  File "/root/gpt-researcher/gpt_researcher/utils/llm.py", line 59, in create_chat_completion
    response = await provider.get_chat_response(
  File "/root/gpt-researcher/gpt_researcher/llm_provider/generic/base.py", line 96, in get_chat_response
    output = await self.llm.ainvoke(messages)
  File "/usr/local/lib/python3.10/dist-packages/langchain_core/language_models/chat_models.py", line 298, in ainvoke
    llm_result = await self.agenerate_prompt(
  File "/usr/local/lib/python3.10/dist-packages/langchain_core/language_models/chat_models.py", line 787, in agenerate_prompt
    return await self.agenerate(
  File "/usr/local/lib/python3.10/dist-packages/langchain_core/language_models/chat_models.py", line 747, in agenerate
    raise exceptions[0]
  File "/usr/local/lib/python3.10/dist-packages/langchain_core/language_models/chat_models.py", line 923, in _agenerate_with_cache
    result = await self._agenerate(
  File "/usr/local/lib/python3.10/dist-packages/langchain_community/chat_models/ollama.py", line 323, in _agenerate
    final_chunk = await self._achat_stream_with_aggregation(
  File "/usr/local/lib/python3.10/dist-packages/langchain_community/chat_models/ollama.py", line 244, in _achat_stream_with_aggregation
    async for stream_resp in self._acreate_chat_stream(messages, stop, **kwargs):
  File "/usr/local/lib/python3.10/dist-packages/langchain_community/chat_models/ollama.py", line 203, in _acreate_chat_stream
    async for stream_resp in self._acreate_stream(
  File "/usr/local/lib/python3.10/dist-packages/langchain_community/llms/ollama.py", line 314, in _acreate_stream
    async with session.post(
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client.py", line 1353, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client.py", line 657, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/connector.py", line 564, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/connector.py", line 975, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/connector.py", line 1350, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/connector.py", line 1319, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/connector.py", line 1088, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:11434 ssl:default [Multiple exceptions: [Errno 111] Connect call failed ('::1', 11434, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 11434)]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/websockets/websockets_impl.py", line 244, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 152, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 77, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 362, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 95, in app
    await wrap_app_handling_exceptions(app, session)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 93, in app
    await func(session)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 367, in app
    await dependant.call(**values)
  File "/root/gpt-researcher/backend/server.py", line 89, in websocket_endpoint
    report = await manager.start_streaming(
  File "/root/gpt-researcher/backend/websocket_manager.py", line 60, in start_streaming
    report = await run_agent(task, report_type, report_source, source_urls, tone, websocket, headers)
  File "/root/gpt-researcher/backend/websocket_manager.py", line 97, in run_agent
    report = await researcher.run()
  File "/root/gpt-researcher/backend/report_type/basic_report/basic_report.py", line 41, in run
    await researcher.conduct_research()
  File "/root/gpt-researcher/gpt_researcher/master/agent.py", line 115, in conduct_research
    self.agent, self.role = await choose_agent(
  File "/root/gpt-researcher/gpt_researcher/master/actions.py", line 156, in choose_agent
    return await handle_json_error(response)
  File "/root/gpt-researcher/gpt_researcher/master/actions.py", line 167, in handle_json_error
    json_string = extract_json_with_regex(response)
  File "/root/gpt-researcher/gpt_researcher/master/actions.py", line 183, in extract_json_with_regex
    json_match = re.search(r"{.*?}", response, re.DOTALL)
  File "/usr/lib/python3.10/re.py", line 200, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
INFO:     connection closed"
```

Here is my .env file: 

```
# Use ollama for both, LLM and EMBEDDING provider
LLM_PROVIDER=ollama

# Ollama endpoint to use
OLLAMA_BASE_URL=http://100.111.84.5:11434

# Specify one of the LLM models supported by Ollama
FAST_LLM_MODEL=phi3:latest
# Specify one of the LLM models supported by Ollama 
SMART_LLM_MODEL=llama3.1:latest
# The temperature to use, defaults to 0.55
TEMPERATURE=0.55

EMBEDDING_PROVIDER=ollama
# Specify one of the embedding models supported by Ollama 
OLLAMA_EMBEDDING_MODEL=nomic-embed-text
```

It feels like the environment variable isn't being picked up properly.

**Comment by andyuan997** [comment]
The default access address and listening port of Ollama API is `http://localhost:11434`, so I think the environment variables are not read.
Try looking at adding the following code to `main.py`.
```
from dotenv import load_dotenv
load_dotenv()
```
Eventually it becomes:
```
from dotenv import load_dotenv

load_dotenv()

from backend.server import app

if __name__ == "__main__":
    import uvicorn
    from dotenv import load_dotenv

    load_dotenv()

    uvicorn.run(app, host="0.0.0.0", port=8000)
```

In my case, I used this method to read the environment variables correctly.

**Comment by juha-leivo** [comment]
I have the same problem. Modification given by andyuan997 doesn't change the behavior. I tested with SSH tunnel and when local port is forwarded to remote it works as expected. All other environment variables are read.

**Comment by mdlmarkham** [comment]
Thanks for the help. I did a fresh install, followed the referenced guide and it's working properly.
