### ISSUE TITLE
ModuleNotFoundError: No module named 'Exa'

### ISSUE THREAD

**Issue by alextjp** [assafelovic/gpt-researcher#826]
Running the application/code in Pycharm (python 3.10 interpreter), I've installed all the dependencies for Exa. After several restarts, still getting the same error, No module named 'Exa', cant run the application at all. 

This is what my terminal log looks like:

INFO:     Started server process [56976]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:61034 - "GET / HTTP/1.1" 200 OK
INFO:     ('127.0.0.1', 61043) - "WebSocket /ws" [accepted]
INFO:     connection open
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/alexsar/miniforge3/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 244, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)  # type: ignore[func-returns-value]
  File "/Users/alexsar/miniforge3/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/Users/alexsar/miniforge3/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/alexsar/miniforge3/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/alexsar/miniforge3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 151, in __call__
    await self.app(scope, receive, send)
  File "/Users/alexsar/miniforge3/lib/python3.10/site-packages/starlette/middleware/cors.py", line 77, in __call__
    await self.app(scope, receive, send)
  File "/Users/alexsar/miniforge3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/alexsar/miniforge3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/alexsar/miniforge3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/alexsar/miniforge3/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/alexsar/miniforge3/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/Users/alexsar/miniforge3/lib/python3.10/site-packages/starlette/routing.py", line 373, in handle
    await self.app(scope, receive, send)
  File "/Users/alexsar/miniforge3/lib/python3.10/site-packages/starlette/routing.py", line 96, in app
    await wrap_app_handling_exceptions(app, session)(scope, receive, send)
  File "/Users/alexsar/miniforge3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/alexsar/miniforge3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/alexsar/miniforge3/lib/python3.10/site-packages/starlette/routing.py", line 94, in app
    await func(session)
  File "/Users/alexsar/miniforge3/lib/python3.10/site-packages/fastapi/routing.py", line 348, in app
    await dependant.call(**values)
  File "/Users/alexsar/Documents/gpt-researcher/gpt-researcher/backend/server.py", line 89, in websocket_endpoint
    report = await manager.start_streaming(
  File "/Users/alexsar/Documents/gpt-researcher/gpt-researcher/backend/websocket_manager.py", line 60, in start_streaming
    report = await run_agent(task, report_type, report_source, source_urls, tone, websocket, headers)
  File "/Users/alexsar/Documents/gpt-researcher/gpt-researcher/backend/websocket_manager.py", line 97, in run_agent
    report = await researcher.run()
  File "/Users/alexsar/Documents/gpt-researcher/gpt-researcher/backend/report_type/basic_report/basic_report.py", line 29, in run
    researcher = GPTResearcher(
  File "/Users/alexsar/Documents/gpt-researcher/gpt-researcher/gpt_researcher/master/agent.py", line 65, in __init__
    self.retrievers = get_retrievers(self.headers, self.cfg)
  File "/Users/alexsar/Documents/gpt-researcher/gpt-researcher/gpt_researcher/master/actions.py", line 110, in get_retrievers
    return [get_retriever(r) or get_default_retriever() for r in retrievers]
  File "/Users/alexsar/Documents/gpt-researcher/gpt-researcher/gpt_researcher/master/actions.py", line 110, in <listcomp>
    return [get_retriever(r) or get_default_retriever() for r in retrievers]
  File "/Users/alexsar/Documents/gpt-researcher/gpt-researcher/gpt_researcher/master/actions.py", line 55, in get_retriever
    from gpt_researcher.retrievers import TavilySearch
  File "/Users/alexsar/Documents/gpt-researcher/gpt-researcher/gpt_researcher/retrievers/__init__.py", line 12, in <module>
    from .exa.exa import ExaSearch
  File "/Users/alexsar/Documents/gpt-researcher/gpt-researcher/gpt_researcher/retrievers/exa/exa.py", line 3, in <module>
    import Exa
ModuleNotFoundError: No module named 'Exa'
INFO:     connection closed

**Comment by alextjp** [comment]
Alright, I figured it out pretty easily, the proper install and import are:

pip install exa_py

from exa_py import Exa

**Comment by assafelovic** [comment]
Yup, we've removed the required installations for these to reduce the package size. So any additional LLM or search provider would require installing the proper library. I'll add better error logs for this. Thanks for raising it!
