### ISSUE TITLE
[ERROR] KeyError: 'FAST_LLM' - Connection Closed 

### ISSUE THREAD

**Issue by Greatz08** [assafelovic/gpt-researcher#901]
I did selfhost using docker and gui is opening as build was successful so no issues on that part and here are my following .env confs and console error   : 

```
OPENAI_API_KEY="123"
OPENAI_API_BASE="https://ollama.hue.com/v1"
OLLAMA_BASE_URL="https://ollama.hue.com/"
FAST_LLM=qwen2.5:latest
OLLAMA_EMBEDDING_MODEL=snowflake-arctic-embed:latest
EMBEDDING_PROVIDER=ollama
SMART_LLM=qwen2.5:latest
TAVILY_API_KEY=tvly-mZF7aeIh3IPZNaQPzhG84xMH56UjP
DOC_PATH=./my-docs

```

> INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     172.20.0.1:31110 - "GET / HTTP/1.1" 200 OK
INFO:     172.20.0.1:31110 - "GET /site/styles.css HTTP/1.1" 304 Not Modified
INFO:     172.20.0.1:31116 - "GET /site/scripts.js HTTP/1.1" 304 Not Modified
INFO:     172.20.0.1:31110 - "GET /static/gptr-logo.png HTTP/1.1" 304 Not Modified
INFO:     ('172.20.0.1', 31128) - "WebSocket /ws" [accepted]
INFO:     connection open
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 242, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 152, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 77, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 362, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 95, in app
    await wrap_app_handling_exceptions(app, session)(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 93, in app
    await func(session)
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 383, in app
    await dependant.call(**solved_result.values)
  File "/usr/src/app/backend/server/server.py", line 142, in websocket_endpoint
    await handle_websocket_communication(websocket, manager)
  File "/usr/src/app/backend/server/server_utils.py", line 117, in handle_websocket_communication
    await handle_start_command(websocket, data, manager)
  File "/usr/src/app/backend/server/server_utils.py", line 28, in handle_start_command
    report = await manager.start_streaming(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/backend/server/websocket_manager.py", line 61, in start_streaming
    report = await run_agent(task, report_type, report_source, source_urls, tone, websocket, headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/backend/server/websocket_manager.py", line 95, in run_agent
    report = await researcher.run()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/backend/report_type/basic_report/basic_report.py", line 30, in run
    researcher = GPTResearcher(
                 ^^^^^^^^^^^^^^
  File "/usr/src/app/gpt_researcher/master/agent/master.py", line 41, in __init__
    self.cfg = Config(config_path)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/gpt_researcher/config/config.py", line 27, in __init__
    value = self.convert_env_value(key, env_value, BaseConfig.__annotations__[key])
                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
KeyError: 'FAST_LLM'
INFO:     connection closed

![image](https://github.com/user-attachments/assets/775166e8-2742-40ff-81ff-469469e644fb)


I believe it is either ollama related issue in the code or i am not mentioning something important in .env file or i am mentioning in wrong way idk so please guide me to fix it. Btw i am using arch linux and i am using latest ollama with qwen2.5:latest as model and snowflake-arctic-embed:latest as embedded model and it is working fine in cli and in openwebgui too plus I am using latest build of this project ( build today only :-) )

**Comment by rajofearth** [comment]
i am having the same issue . 
here is the cli output:
```
\gpt-researcher> python -m uvicorn main:app
INFO:     Started server process [5812]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     ('127.0.0.1', 50452) - "WebSocket /ws" [accepted]
INFO:     connection open
Warning: Configuration '' not found. Using default configuration.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\Quantum Quasar\AppData\Local\Programs\Python\Python312\Lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 242, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Quantum Quasar\AppData\Local\Programs\Python\Python312\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Quantum Quasar\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\Quantum Quasar\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Quantum Quasar\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\errors.py", line 152, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\Quantum Quasar\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\cors.py", line 77, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\Quantum Quasar\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\Quantum Quasar\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\Users\Quantum Quasar\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Quantum Quasar\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Quantum Quasar\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\Users\Quantum Quasar\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 362, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Quantum Quasar\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 95, in app
    await wrap_app_handling_exceptions(app, session)(scope, receive, send)
  File "C:\Users\Quantum Quasar\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\Users\Quantum Quasar\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Quantum Quasar\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 93, in app
    await func(session)
  File "C:\Users\Quantum Quasar\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 383, in app
    await dependant.call(**solved_result.values)
  File "C:\Users\Quantum Quasar\Programs\gpt-researcher\backend\server\server.py", line 142, in websocket_endpoint
    await handle_websocket_communication(websocket, manager)
  File "C:\Users\Quantum Quasar\Programs\gpt-researcher\backend\server\server_utils.py", line 117, in handle_websocket_communication
    await handle_start_command(websocket, data, manager)
  File "C:\Users\Quantum Quasar\Programs\gpt-researcher\backend\server\server_utils.py", line 28, in handle_start_command
    report = await manager.start_streaming(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Quantum Quasar\Programs\gpt-researcher\backend\server\websocket_manager.py", line 61, in start_streaming
    report = await run_agent(task, report_type, report_source, source_urls, tone, websocket, headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Quantum Quasar\Programs\gpt-researcher\backend\server\websocket_manager.py", line 95, in run_agent
    report = await researcher.run()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Quantum Quasar\Programs\gpt-researcher\backend\report_type\basic_report\basic_report.py", line 30, in run
    researcher = GPTResearcher(
                 ^^^^^^^^^^^^^^
  File "C:\Users\Quantum Quasar\Programs\gpt-researcher\gpt_researcher\master\agent\master.py", line 41, in __init__
    self.cfg = Config(config_path)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Quantum Quasar\Programs\gpt-researcher\gpt_researcher\config\config.py", line 27, in __init__
    value = self.convert_env_value(key, env_value, BaseConfig.__annotations__[key])
                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
KeyError: 'FAST_LLM'
INFO:     connection closed
```
And yeah this is my .env :
```
GROQ_API_KEY=gsk_******
FAST_LLM=groq:Mixtral-8x7b-32768
SMART_LLM=groq:Llama3-70b-8192
TEMPERATURE=0.55
TAVILY_API_KEY=tvly-******
DOC_PATH=./my-docs
```

**Comment by kesamet** [comment]
Created a PR to fix this: https://github.com/assafelovic/gpt-researcher/pull/902
