### ISSUE TITLE
Ollama not working

### ISSUE THREAD

**Issue by Davery92** [assafelovic/gpt-researcher#904]
Running both the docker instance as well as the uvicorn instance, I can't connect to my ollama instance which is hosted on the same machine: I've used the documentation for using ollama, I've looked through past issues to look for solutions, and I have tried every different way to do it. I've tried every permeation on server address I could in the .env file, I've even tried putting the environment variables in the docker-compose.yaml. However no matter what I do, I get the following error:
2024-10-13 20:57:38 INFO:     Started server process [1]
2024-10-13 20:57:38 INFO:     Waiting for application startup.
2024-10-13 20:57:38 INFO:     Application startup complete.
2024-10-13 20:57:38 INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2024-10-13 20:57:58 INFO:     ('172.21.0.1', 56008) - "WebSocket /ws" [accepted]
2024-10-13 20:57:58 INFO:     connection open
2024-10-13 20:57:58 ERROR:    Exception in ASGI application
2024-10-13 20:57:58 Traceback (most recent call last):
2024-10-13 20:57:58   File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1091, in _wrap_create_connection
2024-10-13 20:57:58     sock = await aiohappyeyeballs.start_connection(
2024-10-13 20:57:58            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-13 20:57:58   File "/usr/local/lib/python3.11/site-packages/aiohappyeyeballs/impl.py", line 104, in start_connection
2024-10-13 20:57:58     raise first_exception
2024-10-13 20:57:58   File "/usr/local/lib/python3.11/site-packages/aiohappyeyeballs/impl.py", line 82, in start_connection
2024-10-13 20:57:58     sock = await _connect_sock(
2024-10-13 20:57:58            ^^^^^^^^^^^^^^^^^^^^
2024-10-13 20:57:58   File "/usr/local/lib/python3.11/site-packages/aiohappyeyeballs/impl.py", line 174, in _connect_sock
2024-10-13 20:57:58     await loop.sock_connect(sock, address)
2024-10-13 20:57:58   File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 634, in sock_connect
2024-10-13 20:57:58     return await fut
2024-10-13 20:57:58            ^^^^^^^^^
2024-10-13 20:57:58   File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 674, in _sock_connect_cb
2024-10-13 20:57:58     raise OSError(err, f'Connect call failed {address}')
2024-10-13 20:57:58 ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 11434)
2024-10-13 20:57:58 
2024-10-13 20:57:58 The above exception was the direct cause of the following exception:
2024-10-13 20:57:58 
2024-10-13 20:57:58 Traceback (most recent call last):
2024-10-13 20:57:58   File "/usr/src/app/gpt_researcher/master/actions/query_processing.py", line 30, in choose_agent
2024-10-13 20:57:58     response = await create_chat_completion(
2024-10-13 20:57:58                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-13 20:57:58   File "/usr/src/app/gpt_researcher/utils/llm.py", line 60, in create_chat_completion
2024-10-13 20:57:58     response = await provider.get_chat_response(
2024-10-13 20:57:58                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-13 20:57:58   File "/usr/src/app/gpt_researcher/llm_provider/generic/base.py", line 96, in get_chat_response
2024-10-13 20:57:58     output = await self.llm.ainvoke(messages)
2024-10-13 20:57:58              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-13 20:57:58   File "/usr/local/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 298, in ainvoke
2024-10-13 20:57:58     llm_result = await self.agenerate_prompt(
2024-10-13 20:57:58                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-13 20:57:58   File "/usr/local/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 787, in agenerate_prompt
2024-10-13 20:57:58     return await self.agenerate(
2024-10-13 20:57:58            ^^^^^^^^^^^^^^^^^^^^^
2024-10-13 20:57:58   File "/usr/local/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 747, in agenerate
2024-10-13 20:57:58     raise exceptions[0]
2024-10-13 20:57:58   File "/usr/local/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 923, in _agenerate_with_cache
2024-10-13 20:57:58     result = await self._agenerate(
2024-10-13 20:57:58              ^^^^^^^^^^^^^^^^^^^^^^
2024-10-13 20:57:58   File "/usr/local/lib/python3.11/site-packages/langchain_community/chat_models/ollama.py", line 323, in _agenerate
2024-10-13 20:57:58     final_chunk = await self._achat_stream_with_aggregation(
2024-10-13 20:57:58                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-13 20:57:58   File "/usr/local/lib/python3.11/site-packages/langchain_community/chat_models/ollama.py", line 244, in _achat_stream_with_aggregation
2024-10-13 20:57:58     async for stream_resp in self._acreate_chat_stream(messages, stop, **kwargs):
2024-10-13 20:57:58   File "/usr/local/lib/python3.11/site-packages/langchain_community/chat_models/ollama.py", line 203, in _acreate_chat_stream
2024-10-13 20:57:58     async for stream_resp in self._acreate_stream(
2024-10-13 20:57:58   File "/usr/local/lib/python3.11/site-packages/langchain_community/llms/ollama.py", line 314, in _acreate_stream
2024-10-13 20:57:58     async with session.post(
2024-10-13 20:57:58   File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1359, in __aenter__
2024-10-13 20:57:58     self._resp: _RetType = await self._coro
2024-10-13 20:57:58                            ^^^^^^^^^^^^^^^^
2024-10-13 20:57:58   File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 663, in _request
2024-10-13 20:57:58     conn = await self._connector.connect(
2024-10-13 20:57:58            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-13 20:57:58   File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 563, in connect
2024-10-13 20:57:58     proto = await self._create_connection(req, traces, timeout)
2024-10-13 20:57:58             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-13 20:57:58   File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1032, in _create_connection
2024-10-13 20:57:58     _, proto = await self._create_direct_connection(req, traces, timeout)
2024-10-13 20:57:58                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-13 20:57:58   File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1366, in _create_direct_connection
2024-10-13 20:57:58     raise last_exc
2024-10-13 20:57:58   File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1335, in _create_direct_connection
2024-10-13 20:57:58     transp, proto = await self._wrap_create_connection(
2024-10-13 20:57:58                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-13 20:57:58   File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1106, in _wrap_create_connection
2024-10-13 20:57:58     raise client_error(req.connection_key, exc) from exc
2024-10-13 20:57:58 aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:11434 ssl:default [Connect call failed ('127.0.0.1', 11434)]
2024-10-13 20:57:58 
2024-10-13 20:57:58 During handling of the above exception, another exception occurred:
2024-10-13 20:57:58 
2024-10-13 20:57:58 Traceback (most recent call last):
2024-10-13 20:57:58   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 242, in run_asgi
2024-10-13 20:57:58     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)  # type: ignore[func-returns-value]
2024-10-13 20:57:58              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-13 20:57:58   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
2024-10-13 20:57:58     return await self.app(scope, receive, send)
2024-10-13 20:57:58            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-13 20:57:58   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-10-13 20:57:58     await super().__call__(scope, receive, send)
2024-10-13 20:57:58   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 113, in __call__
2024-10-13 20:57:58     await self.middleware_stack(scope, receive, send)
2024-10-13 20:57:58   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 152, in __call__
2024-10-13 20:57:58     await self.app(scope, receive, send)
2024-10-13 20:57:58   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 77, in __call__
2024-10-13 20:57:58     await self.app(scope, receive, send)
2024-10-13 20:57:58   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
2024-10-13 20:57:58     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-10-13 20:57:58   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
2024-10-13 20:57:58     raise exc
2024-10-13 20:57:58   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
2024-10-13 20:57:58     await app(scope, receive, sender)
2024-10-13 20:57:58   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 715, in __call__
2024-10-13 20:57:58     await self.middleware_stack(scope, receive, send)
2024-10-13 20:57:58   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 735, in app
2024-10-13 20:57:58     await route.handle(scope, receive, send)
2024-10-13 20:57:58   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 362, in handle
2024-10-13 20:57:58     await self.app(scope, receive, send)
2024-10-13 20:57:58   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 95, in app
2024-10-13 20:57:58     await wrap_app_handling_exceptions(app, session)(scope, receive, send)
2024-10-13 20:57:58   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
2024-10-13 20:57:58     raise exc
2024-10-13 20:57:58   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
2024-10-13 20:57:58     await app(scope, receive, sender)
2024-10-13 20:57:58   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 93, in app
2024-10-13 20:57:58     await func(session)
2024-10-13 20:57:58   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 383, in app
2024-10-13 20:57:58     await dependant.call(**solved_result.values)
2024-10-13 20:57:58   File "/usr/src/app/backend/server/server.py", line 142, in websocket_endpoint
2024-10-13 20:57:58     await handle_websocket_communication(websocket, manager)
2024-10-13 20:57:58   File "/usr/src/app/backend/server/server_utils.py", line 117, in handle_websocket_communication
2024-10-13 20:57:58     await handle_start_command(websocket, data, manager)
2024-10-13 20:57:58   File "/usr/src/app/backend/server/server_utils.py", line 28, in handle_start_command
2024-10-13 20:57:58     report = await manager.start_streaming(
2024-10-13 20:57:58              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-13 20:57:58   File "/usr/src/app/backend/server/websocket_manager.py", line 61, in start_streaming
2024-10-13 20:57:58     report = await run_agent(task, report_type, report_source, source_urls, tone, websocket, headers)
2024-10-13 20:57:58              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-13 20:57:58   File "/usr/src/app/backend/server/websocket_manager.py", line 95, in run_agent
2024-10-13 20:57:58     report = await researcher.run()
2024-10-13 20:57:58              ^^^^^^^^^^^^^^^^^^^^^^
2024-10-13 20:57:58   File "/usr/src/app/backend/report_type/basic_report/basic_report.py", line 41, in run
2024-10-13 20:57:58     await researcher.conduct_research()
2024-10-13 20:57:58   File "/usr/src/app/gpt_researcher/master/agent/master.py", line 74, in conduct_research
2024-10-13 20:57:58     self.agent, self.role = await choose_agent(
2024-10-13 20:57:58                             ^^^^^^^^^^^^^^^^^^^
2024-10-13 20:57:58   File "/usr/src/app/gpt_researcher/master/actions/query_processing.py", line 47, in choose_agent
2024-10-13 20:57:58     return await handle_json_error(response)
2024-10-13 20:57:58            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-13 20:57:58   File "/usr/src/app/gpt_researcher/master/actions/query_processing.py", line 58, in handle_json_error
2024-10-13 20:57:58     json_string = extract_json_with_regex(response)
2024-10-13 20:57:58                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-13 20:57:58   File "/usr/src/app/gpt_researcher/master/actions/query_processing.py", line 74, in extract_json_with_regex
2024-10-13 20:57:58     json_match = re.search(r"{.*?}", response, re.DOTALL)
2024-10-13 20:57:58                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-13 20:57:58   File "/usr/local/lib/python3.11/re/__init__.py", line 176, in search
2024-10-13 20:57:58     return _compile(pattern, flags).search(string)
2024-10-13 20:57:58            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-13 20:57:58 TypeError: expected string or bytes-like object, got 'NoneType'
2024-10-13 20:57:58 INFO:     connection closed

This is the .env:
OPENAI_API_KEY="123"
OPENAI_API_BASE="http://127.0.0.1:11434/v1"
OLLAMA_BASE_URL="http://127.0.0.1:11434/"
FAST_LLM=ollama:llama3.1
SMART_LLM=ollama:qwen2.5:14b
OLLAMA_EMBEDDING_MODEL=nomic-embed-text
EMBEDDING_PROVIDER=ollama
DOC_PATH=./my-docs

I've tried localhost, my server ip, host.docker.internal. Everything comes back with the same error.
I feel like I'm missing something. Yesterday I was having the KeyError and that's been resolved since the most recent pull request.

**Comment by Davery92** [comment]
Forgot to mention I also tried the test script in the documentation (had to modify it slightly, base_url was defined twice) but it successfully returned a response to the url http://127.0.0.1:11434

**Comment by Davery92** [comment]
I figured it out. Remove the trailing / in the ollama base url and use host.docker.internal for the docker version and it works

**Comment by PieBru** [comment]
See https://github.com/assafelovic/gpt-researcher/issues/908#issuecomment-2414310806
